#!/bin/bash
# admin

PROJECT_OUSER=$(who -m | awk '{print $1}')

# Check if the user is root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Pass all the arguments to the Python script
export PROJECT_NAME=logistic && export PROJECT_OUSER && export PROJECT_PORT=3004 && export PROJECT_VERSION=42 && export PROJECT_BASE_DIR=$(dirname "$(readlink -f "$0")") && python3 cli/export.py "$@"
